spring:
  h2:
    console:
      enabled: true
      path: /h2-ui
  datasource:
    url: jdbc:h2:file:./testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8088

tenpo:
  app:
    jwtCookieName: tenpoCookie
    jwtSecrete: tenpoSecretKey
    jwtExpirationMs: 60000
    jwtRefreshExpirationMs: 120000

logging:
  level:
    root: info
    org.zalando.logbook: TRACE

logbook:
  exclude: /actuator/**, /swagger-ui**, /api-docs**
  format:
    style: json

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

resilience4j.circuitbreaker:
  instances:
    service1:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException